version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"  # 3000 (host) -> 80 (nginx inside container)
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
